parameters:
    skautis.skautis_class: 'Skautis\Skautis'
    skautis.skautis_factory_class: 'SkautisBundle\Skautis\SkautisFactory'
    skautis.ws_class: 'SkautisBundle\Skautis\Wsdl\StopwatchWebService'
    skautis.ws_factory_class: 'SkautisBundle\Skautis\Wsdl\StopwatchWebServiceFactory'
    skautis.session_adapter_class: 'SkautisBundle\Skautis\SessionAdapter'
    skautis.data_collector_class: 'SkautisBundle\Profiler\SkautisDataCollector'
    skautis.config_class: 'Skautis\Config'
    skautis.wsdl_manager_class: 'Skautis\Wsdl\WsdlManager'
    skautis.user_class: 'Skautis\User'

services:
    skautis.ws_factory:
        class: "%skautis.ws_factory_class%"
        arguments:
            - "%skautis.ws_class%"
        calls:
            - [ setStopwatch, [@debug.stopwatch]]

    skautis.wsdl_manager:
        class: "%skautis.wsdl_manager_class%"
        arguments:
            - @skautis.ws_factory
            - @skautis.config

    skautis.session_adapter:
        class: "%skautis.session_adapter_class%"
        arguments:
            - @session

    skautis.config:
        class: "%skautis.config_class%"
        arguments:
            - "%skautis.app_id%"
            - "%skautis.test_mode%"
            - "%skautis.profiler%"
            - "%skautis.cache%"
            - "%skautis.compression%"


    skautis.user:
        class: "%skautis.user_class%"
        arguments:
            - @skautis.wsdl_manager
            - @skautis.session_adapter

    skautis.skautis_factory:
        class: '%skautis.skautis_factory_class%'

    skautis:
        class: "%skautis.skautis_class%"
        factory: [@skautis.skautis_factory, 'createSkautis']
        arguments:
            - @skautis.wsdl_manager
            - @skautis.user
            - "%skautis.profiler%"

    data_collector.skautis_collector:
        class: "%skautis.data_collector_class%"
        arguments:
            - @skautis
        tags:
            - { name: data_collector, template: "SkautisBundle:Collector:template", id: "skautis_collector"}

