parameters:
    skautis.cache_class: 'SkautisBundle\Skautis\Wsdl\Decorator\Cache\DoctrineCache'
    skautis.cache.ttl: 0
    skautis.user.provider_class: 'asd'


services:
    skautis.ws_factory:
        class: 'SkautisBundle\Skautis\Wsdl\StopwatchWebServiceFactory'
        arguments:
            - 'SkautisBundle\Skautis\Wsdl\StopwatchWebService'
        calls:
            - [ setStopwatch, ["@debug.stopwatch"]]

    skautis.wsdl_manager:
        class: 'Skautis\Wsdl\WsdlManager'
        arguments:
            - "@skautis.ws_factory"
            - "@skautis.config"

    skautis.session_adapter:
        class: 'SkautisBundle\Skautis\SessionAdapter'
        arguments:
            - "@session"

    skautis.config:
        class: 'Skautis\Config'
        arguments:
            - "%skautis.app_id%"
            - "%skautis.test_mode%"
            - "%skautis.profiler%"
            - "%skautis.wsdl.cache%"
            - "%skautis.wsdl.compression%"

    skautis.user:
        class: 'Skautis\User'
        arguments:
            - "@skautis.wsdl_manager"
            - "@skautis.session_adapter"

    skautis.skautis_factory:
        class: 'SkautisBundle\Skautis\SkautisFactory'

    skautis:
        class: "Skautis\Skautis"
        factory: ["@skautis.skautis_factory", 'createSkautis']
        arguments:
            - "@skautis.wsdl_manager"
            - "@skautis.user"
            - "%skautis.profiler%"

    data_collector.skautis_collector:
        class: 'SkautisBundle\Profiler\SkautisDataCollector'
        arguments:
            - "@skautis"
        tags:
            - { name: data_collector, template: "SkautisBundle:Collector:template", id: "skautis_collector"}

    skautis.monolog.processor:
        class: 'SkautisBundle\Monolog\SkautisProcessor'
        arguments:  ["@skautis"]
        tags:
            - { name: monolog.processor, method: processRecord, channel: skautis }

    skautis.security.authentication.fos_user_registrator:
        class: 'SkautisBundle\Security\Authentication\Registrator\FosUserRegistrator'
        arguments: ["@skautis", "@?fos_user.user_manager"]


    skautis.security_authentication.skautis_logout_handler:
        class:  'SkautisBundle\Security\Http\Logout\SkautisLogoutHandler'
        arguments: [ "@skautis" ]
        public: false


    skautis.security.authentication.connector:
        class: 'SkautisBundle\Security\Authentication\Connector\DoctrineUserConnector'
        arguments: ["@doctrine.orm.entity_manager"]


    skautis.user_loader:
        class: 'SkautisBundle\Security\Authentication\UserLoader'
        arguments:
            - false
            - "@?skautis.security.authentication.connector"
            - false
            - "@?skautis.security.authentication.registrator"


    skautis.authenticator:
        class: 'SkautisBundle\Security\Authentication\SkautisAuthenticator'
        arguments:
            - "@skautis"
            - "@router"
            - "@session"
            - "@skautis.user_loader"
            - false
            - true

    kernel.listener.your_listener_name:
        class: SkautisBundle\EventListener\SkautisExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
