parameters:
    skautis.cache_class: 'SkautisBundle\Skautis\Wsdl\Decorator\Cache\DoctrineCache'
    skautis.cache.ttl: 0
    skautis.user.provider_class: 'asd'


services:
    skautis.ws_factory:
        class: 'SkautisBundle\Skautis\Wsdl\StopwatchWebServiceFactory'
        arguments:
            - 'SkautisBundle\Skautis\Wsdl\StopwatchWebService'
        calls:
            - [ setStopwatch, ["@debug.stopwatch"]]

    skautis.wsdl_manager:
        class: 'Skautis\Wsdl\WsdlManager'
        arguments:
            - "@skautis.ws_factory"
            - "@skautis.config"

    skautis.session_adapter:
        class: 'SkautisBundle\Skautis\SessionAdapter'
        arguments:
            - "@session"

    skautis.config:
        class: 'Skautis\Config'
        arguments:
            - "%skautis.app_id%"
            - "%skautis.test_mode%"
            - "%skautis.profiler%"
            - "%skautis.wsdl.cache%"
            - "%skautis.wsdl.compression%"

    skautis.user:
        class: 'Skautis\User'
        arguments:
            - "@skautis.wsdl_manager"
            - "@skautis.session_adapter"

    skautis.skautis_factory:
        class: 'SkautisBundle\Skautis\SkautisFactory'

    skautis:
        class: "Skautis\Skautis"
        factory: ["@skautis.skautis_factory", 'createSkautis']
        arguments:
            - "@skautis.wsdl_manager"
            - "@skautis.user"
            - "%skautis.profiler%"

    data_collector.skautis_collector:
        class: 'SkautisBundle\Profiler\SkautisDataCollector'
        arguments:
            - "@skautis"
        tags:
            - { name: data_collector, template: "SkautisBundle:Collector:template", id: "skautis_collector"}

    skautis.monolog.processor:
        class: 'SkautisBundle\Monolog\SkautisProcessor'
        arguments:  ["@skautis"]
        tags:
            - { name: monolog.processor, method: processRecord, channel: skautis }

    skautis.security.authentication.fos_user_registrator:
        class: 'SkautisBundle\Security\Authentication\FosUserRegistrator'
        arguments: ["@skautis", "@?fos_user.user_manager"]

    skautis.user.provider:
        class: "%skautis.user.provider_class%"
        public: false

    skautis.security.authentication.provider:
        class: 'SkautisBundle\Security\Core\Authentication\Provider\SkautisProvider'
        arguments: ["@skautis.user.provider", "%kernel.cache_dir%/security/nonces", "@skautis.security.authentication.connector", "@?skautis.security.authentication.registrator", false]
        public: false

    skautis.security.authentication.listener:
        class: 'SkautisBundle\Security\Http\Firewall\SkautisListener'
        arguments: ["@security.token_storage", "@security.authentication.manager", "@skautis", "@session"]
        public: false

    skautis.security_authentication.skautis_logout_handler:
        class:  'SkautisBundle\Security\Http\Logout\SkautisLogoutHandler'
        arguments: [ "@skautis" ]
        public: false

    skautis.security_authentication.skautis_entry_point:
        class: 'SkautisBundle\Security\Http\EntryPoint\SkautisEntryPoint'
        arguments: [ "@router" ]
        public: false

    skautis.security.authentication.connector:
        class: 'SkautisBundle\Security\Authentication\DoctrineUserConnector'
        arguments: ["@doctrine.orm.entity_manager"]

#    skautis.security.authentication.registrator:
#        abstract: true

    kernel.listener.your_listener_name:
        class: SkautisBundle\EventListener\SkautisExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
