tools:
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
    php_cpd:
        enabled: true
        excluded_dirs: ["docs", "tests", "vendor"]
    php_loc:
        enabled: true
        excluded_dirs: ["docs", "tests", "vendor"]
    php_mess_detector:
        enabled: true
    php_pdepend:
        enabled: true
        excluded_dirs: ["docs", "tests", "vendor"]
    php_analyzer: true
    php_analyzer: true
    sensiolabs_security_checker: true
    external_code_coverage:
        timeout: 600